name: project_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 3.0.0
  #cached_network_image: 3.2.1
  easy_debounce: 2.0.1
  #flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  #go_router: 7.1.1
  #google_fonts: 4.0.3
  intl: 0.18.0
  json_path: 0.4.1
  page_transition: 2.0.4
  #path_provider: 2.0.14
  #path_provider_android: 2.0.25
  #path_provider_foundation: 2.2.2
  #path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  #shared_preferences: 2.0.15
  #shared_preferences_android: 2.1.0
  #shared_preferences_ios: 2.1.1
  #shared_preferences_platform_interface: 2.2.0
  #shared_preferences_web: 2.1.0
  #sqflite: 2.2.6
  timeago: 3.2.2
  #url_launcher: 6.1.10
  #url_launcher_android: 6.0.27
  #url_launcher_ios: 6.1.4
  #url_launcher_platform_interface: 2.1.2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: SegoeMarker
      fonts:
        - asset: assets/fonts/SegoeMarker.ttf
    - family: aldhabi
      fonts:
        - asset: assets/fonts/aldhabi.ttf